
var DICIONARIO = [
    "FAMÍLIA", "PAPAI", "MAMÃE", "GALINHA", "CACHORRO", "ALMOÇO", "DIA", "MANIA",
    "BARATA", "LADRÃO", "INSETICIDA", "CADEADO", "PORTÃO",
    "BEBÊ", "DOEANTE", "FARMÁCIA", "PLANTÃO", "CHORO", "ESTRIDENTE", "TELEVISÃO",
    "MEDO", "TODOS", "PERDEU", "MARASMO", "FAZENDA", "VIVER", "SANGUE", "ÓDIO",
    "CRIANÇA", "PENSAVA", "BANDIDO", "TIRO", "SOLDADO", "TERROR", "SERTANIA", "ESCOLA", "PROFESSOR", "APRENDEU",
    "IGREJA", "ROUBAR", "DINHEIRO", "VELHINHAS", "CAIXA", "ALTAR",
    "MAR", "VAIJAR", "ESCOLA", "SOLIDÃO"
];
