// Copyright 2015 by Paulo Augusto Peccin. See license.txt distributed with this file.

// MSX International Keyboard Mattix
wmsx.KeyboardKeys = {

    D0             : { m:  [ 0, 0 ], key: "D0",            sn: "0",   ssn: ")",               jsn: " " },
    D1             : { m:  [ 0, 1 ], key: "D1",            sn: "1",   ssn: "!" },
    D2             : { m:  [ 0, 2 ], key: "D2",            sn: "2",   ssn: "@",               jsn: "\"" },
    D3             : { m:  [ 0, 3 ], key: "D3",            sn: "3",   ssn: "#" },
    D4             : { m:  [ 0, 4 ], key: "D4",            sn: "4",   ssn: "$" },
    D5             : { m:  [ 0, 5 ], key: "D5",            sn: "5",   ssn: "%" },
    D6             : { m:  [ 0, 6 ], key: "D6",            sn: "6",   ssn: "^",               jsn: "&" },
    D7             : { m:  [ 0, 7 ], key: "D7",            sn: "7",   ssn: "&",               jsn: "'" },
    D8             : { m:  [ 1, 0 ], key: "D8",            sn: "8",   ssn: "*",               jsn: "(" },
    D9             : { m:  [ 1, 1 ], key: "D9",            sn: "9",   ssn: "(",               jsn: ")" },
    MINUS          : { m:  [ 1, 2 ], key: "MINUS",         sn: "-",   ssn: "_",               jsn: "=" },
    EQUAL          : { m:  [ 1, 3 ], key: "EQUAL",         sn: "=",   ssn: "+",   jn: "^",    jsn: "~" },
    BACKSLASH      : { m:  [ 1, 4 ], key: "BACKSLASH",     sn: "\\",  ssn: "|",   jn: "&yen;" },
    OPEN_BRACKET   : { m:  [ 1, 5 ], key: "OPEN_BRACKET",  sn: "[",   ssn: "{",   jn: "@",    jsn: "`" },
    CLOSE_BRACKET  : { m:  [ 1, 6 ], key: "CLOSE_BRACKET", sn: "]",   ssn: "}",   jn: "[",    jsn: "{" },
    SEMICOLON      : { m:  [ 1, 7 ], key: "SEMICOLON",     sn: ";",   ssn: ":",               jsn: "+" },
    QUOTE          : { m:  [ 2, 0 ], key: "QUOTE",         sn: "'",   ssn: "\"",  jn: ":",    jsn: "*" },
    BACKQUOTE      : { m:  [ 2, 1 ], key: "BACKQUOTE",     sn: "`",   ssn: "~",   jn: "]",    jsn: "}" },
    COMMA          : { m:  [ 2, 2 ], key: "COMMA",         sn: ",",   ssn: "<" },
    PERIOD         : { m:  [ 2, 3 ], key: "PERIOD",        sn: ".",   ssn: ">" },
    SLASH          : { m:  [ 2, 4 ], key: "SLASH",         sn: "/",   ssn: "?" },
    DEAD           : { m:  [ 2, 5 ], key: "DEAD",          sn: "DED",             jn: " ",    jsn: "_" },
    A              : { m:  [ 2, 6 ], key: "A",             sn: "A" },
    B              : { m:  [ 2, 7 ], key: "B",             sn: "B" },
    C              : { m:  [ 3, 0 ], key: "C",             sn: "C" },
    D              : { m:  [ 3, 1 ], key: "D",             sn: "D" },
    E              : { m:  [ 3, 2 ], key: "E",             sn: "E" },
    F              : { m:  [ 3, 3 ], key: "F",             sn: "F" },
    G              : { m:  [ 3, 4 ], key: "G",             sn: "G" },
    H              : { m:  [ 3, 5 ], key: "H",             sn: "H" },
    I              : { m:  [ 3, 6 ], key: "I",             sn: "I" },
    J              : { m:  [ 3, 7 ], key: "J",             sn: "J" },
    K              : { m:  [ 4, 0 ], key: "K",             sn: "K" },
    L              : { m:  [ 4, 1 ], key: "L",             sn: "L" },
    M              : { m:  [ 4, 2 ], key: "M",             sn: "M" },
    N              : { m:  [ 4, 3 ], key: "N",             sn: "N" },
    O              : { m:  [ 4, 4 ], key: "O",             sn: "O" },
    P              : { m:  [ 4, 5 ], key: "P",             sn: "P" },
    Q              : { m:  [ 4, 6 ], key: "Q",             sn: "Q" },
    R              : { m:  [ 4, 7 ], key: "R",             sn: "R" },
    S              : { m:  [ 5, 0 ], key: "S",             sn: "S" },
    T              : { m:  [ 5, 1 ], key: "T",             sn: "T" },
    U              : { m:  [ 5, 2 ], key: "U",             sn: "U" },
    V              : { m:  [ 5, 3 ], key: "V",             sn: "V" },
    W              : { m:  [ 5, 4 ], key: "W",             sn: "W" },
    X              : { m:  [ 5, 5 ], key: "X",             sn: "X" },
    Y              : { m:  [ 5, 6 ], key: "Y",             sn: "Y" },
    Z              : { m:  [ 5, 7 ], key: "Z",             sn: "Z" },
    SHIFT          : { m:  [ 6, 0 ], key: "SHIFT",         sn: "SHF" },
    CONTROL        : { m:  [ 6, 1 ], key: "CONTROL",       sn: "CTR" },
    CAPSLOCK       : { m:  [ 6, 3 ], key: "CAPSLOCK",      sn: "CAP" },
    GRAPH          : { m:  [ 6, 2 ], key: "GRAPH",         sn: "GRA" },
    CODE           : { m:  [ 6, 4 ], key: "CODE",          sn: "COD",  jn: "KANA" },
    F1             : { m:  [ 6, 5 ], key: "F1",            sn: "F1" },
    F2             : { m:  [ 6, 6 ], key: "F2",            sn: "F2" },
    F3             : { m:  [ 6, 7 ], key: "F3",            sn: "F3" },
    F4             : { m:  [ 7, 0 ], key: "F4",            sn: "F4" },
    F5             : { m:  [ 7, 1 ], key: "F5",            sn: "F5" },
    ESCAPE         : { m:  [ 7, 2 ], key: "ESCAPE",        sn: "ESC" },
    TAB            : { m:  [ 7, 3 ], key: "TAB",           sn: "TAB" },
    STOP           : { m:  [ 7, 4 ], key: "STOP",          sn: "STP" },
    BACKSPACE      : { m:  [ 7, 5 ], key: "BACKSPACE",     sn: "BS" },
    SELECT         : { m:  [ 7, 6 ], key: "SELECT",        sn: "SEL" },
    ENTER          : { m:  [ 7, 7 ], key: "ENTER",         sn: "RET" },
    SPACE          : { m:  [ 8, 0 ], key: "SPACE",         sn: "SPC" },
    HOME           : { m:  [ 8, 1 ], key: "HOME",          sn: "HOM" },
    INSERT         : { m:  [ 8, 2 ], key: "INSERT",        sn: "INS" },
    DELETE         : { m:  [ 8, 3 ], key: "DELETE",        sn: "DEL" },
    LEFT           : { m:  [ 8, 4 ], key: "LEFT",          sn: "LFT" },
    UP             : { m:  [ 8, 5 ], key: "UP",            sn: "UP" },
    DOWN           : { m:  [ 8, 6 ], key: "DOWN",          sn: "DWN" },
    RIGHT          : { m:  [ 8, 7 ], key: "RIGHT",         sn: "RGH" },
    NUM_MULTIPLY   : { m:  [ 9, 0 ], key: "NUM_MULTIPLY",  sn: "*" },
    NUM_PLUS       : { m:  [ 9, 1 ], key: "NUM_PLUS",      sn: "+" },
    NUM_DIVIDE     : { m:  [ 9, 2 ], key: "NUM_DIVIDE",    sn: "/" },
    NUM_0          : { m:  [ 9, 3 ], key: "NUM_0",         sn: "0" },
    NUM_1          : { m:  [ 9, 4 ], key: "NUM_1",         sn: "1" },
    NUM_2          : { m:  [ 9, 5 ], key: "NUM_2",         sn: "2" },
    NUM_3          : { m:  [ 9, 6 ], key: "NUM_3",         sn: "3" },
    NUM_4          : { m:  [ 9, 7 ], key: "NUM_4",         sn: "4" },
    NUM_5          : { m: [ 10, 0 ], key: "NUM_5",         sn: "5" },
    NUM_6          : { m: [ 10, 1 ], key: "NUM_6",         sn: "6" },
    NUM_7          : { m: [ 10, 2 ], key: "NUM_7",         sn: "7" },
    NUM_8          : { m: [ 10, 3 ], key: "NUM_8",         sn: "8" },
    NUM_9          : { m: [ 10, 4 ], key: "NUM_9",         sn: "9" },
    NUM_MINUS      : { m: [ 10, 5 ], key: "NUM_MINUS",     sn: "-" },
    NUM_COMMA      : { m: [ 10, 6 ], key: "NUM_COMMA",     sn: "," },
    NUM_PERIOD     : { m: [ 10, 7 ], key: "NUM_PERIOD",    sn: "." },
    YES            : { m: [ 11, 1 ], key: "YES",           sn: "YES",    jn: "HAI" },
    NO             : { m: [ 11, 3 ], key: "NO",            sn: "NO",     jn: "IIE" }

};

