// Copyright 2015 by Paulo Augusto Peccin. See license.txt distributed with this file.

wmsx.PeripheralControls = {
    SCREEN_SCALE_X_PLUS: 1, SCREEN_SCALE_Y_PLUS: 2,
    SCREEN_SCALE_X_MINUS: 3, SCREEN_SCALE_Y_MINUS: 4,
    SCREEN_SIZE_PLUS: 5, SCREEN_SIZE_MINUS: 6,
    SCREEN_FULLSCREEN: 11,
    SCREEN_CRT_FILTER: 12, SCREEN_CRT_MODE: 13,
    SCREEN_DEBUG: 15,
    SCREEN_DEFAULTS: 18,

    MACHINE_POWER_TOGGLE: 101, MACHINE_POWER_RESET: 102, MACHINE_SAVE_STATE_FILE: 103,

    JOYSTICKS_TOGGLE_MODE: 201,

    DISKA_LOAD_FILE: 21, DISKA_LOAD_FILE_ALT_POWER: 22, DISKA_LOAD_URL: 23, DISKA_REMOVE: 24, DISKA_EMPTY: 25, DISKA_SAVE_FILE: 26,
    DISKB_LOAD_FILE: 31, DISKB_LOAD_FILE_ALT_POWER: 32, DISKB_LOAD_URL: 33, DISKB_REMOVE: 34, DISKB_EMPTY: 35, DISKB_SAVE_FILE: 36,
    CARTRIDGE1_LOAD_FILE: 41, CARTRIDGE1_LOAD_URL: 42, CARTRIDGE1_REMOVE: 43,
    CARTRIDGE2_LOAD_FILE: 51, CARTRIDGE2_LOAD_URL: 52, CARTRIDGE2_REMOVE: 53,
    TAPE_LOAD_FILE: 61, TAPE_LOAD_FILE_ALT_POWER: 62, TAPE_LOAD_URL: 63, TAPE_REMOVE: 64, TAPE_EMPTY: 65, TAPE_SAVE_FILE: 66,
    TAPE_REWIND: 67, TAPE_TO_END: 68, TAPE_SEEK_FWD: 69, TAPE_SEEK_BACK: 70, TAPE_AUTO_RUN: 71,

    EXIT: 999
};
