// Copyright 2015 by Paulo Augusto Peccin. See license.txt distributed with this file.

wmsx.PeripheralControls = {

    SCREEN_ASPECT_PLUS: 1, SCREEN_ASPECT_MINUS: 2,
    SCREEN_SCALE_PLUS: 3, SCREEN_SCALE_MINUS: 4,
    SCREEN_FULLSCREEN: 11,
    SCREEN_CRT_FILTER: 12, SCREEN_CRT_MODE: 13,
    SCREEN_DEFAULTS: 15,
    SCREEN_OPEN_HELP: 17,
    SCREEN_OPEN_ABOUT: 18,
    SCREEN_OPEN_SETTINGS: 19,

    PASTE_STRING: 301,
    CAPTURE_SCREEN: 401,

    MACHINE_POWER_TOGGLE: 101, MACHINE_POWER_RESET: 102, MACHINE_LOAD_STATE_FILE: 103, MACHINE_SAVE_STATE_FILE: 104,

    KEYBOARD_TOGGLE_HOST_LAYOUT: 201, JOYSTICKS_TOGGLE_MODE: 202, MOUSE_TOGGLE_MODE: 203, TURBO_FIRE_TOGGLE: 204,

    DISK_LOAD_FILE: 20, DISK_LOAD_URL: 22, DISK_LOAD_FILES: 23, DISK_LOAD_ZIP: 24, DISK_REMOVE: 25, DISK_EMPTY: 26, DISK_EMPTY_720: 27, DISK_EMPTY_360: 28, DISK_SAVE_FILE: 29,
    CARTRIDGE_LOAD_FILE: 40, CARTRIDGE_LOAD_URL: 42, CARTRIDGE_REMOVE: 43, CARTRIDGE_LOAD_DATA_FILE: 44, CARTRIDGE_SAVE_DATA_FILE: 45,
    TAPE_LOAD_FILE: 60, TAPE_LOAD_URL: 62, TAPE_REMOVE: 63, TAPE_EMPTY: 64, TAPE_SAVE_FILE: 65,
    TAPE_REWIND: 66, TAPE_TO_END: 67, TAPE_SEEK_FWD: 68, TAPE_SEEK_BACK: 69, TAPE_AUTO_RUN: 70,
    ALL_LOAD_FILE: 80, ALL_LOAD_URL: 81

};
