// Copyright 2015 by Paulo Augusto Peccin. See license.txt distributed with this file.

wmsx.CompressedSystemFilesList = [
    "MSX1_JAP.bios",
    "MSX1_PAL.bios",
    "MSX2_JAP.bios",
    "MSX2_PAL.bios",
    "MSX2EXT_JAP.bios",
    "MSX2EXT_PAL.bios",
    "MSX2P_JAP.bios",
    "MSX2P_PAL.bios",
    "MSX2PEXT_JAP.bios",
    "MSXTR_JAP.bios",
    "MSXTR_PAL.bios",
    "MSXTREXT_JAP.bios",
    "MSXTREXT_PAL.bios",
    "MSXTROPEN_NTSC.bios",
    "KanjiBasicOnly.bios",
    "KanjiBasic2PLogo_NTSC.bios",
    "[Kanji1].rom",
    "[MSXJE].rom",
    "[DiskPatch].rom",
    "[DiskPatchDOS2TR].rom",
    "[Nextor16Patch].rom",
    "[MSXMUSIC].rom",
    "[MSXMUSIC]TR.rom",
    // "[MSXDOS2]v22.rom",      // No more since Nextor support
    "[RAMNormal].rom",
    "[RAMMapper].rom",
    "[SCCExpansion].rom",
    "[SCCIExpansion].rom",
    "[PACExpansion].rom",
    "[MegaRAM].rom",
    "[V9990].rom",
    "[Empty].rom",
    "Disk16MHeader.dat",
    "Disk32MHeader.dat",
    "Disk64MHeader.dat",
    "Disk128MHeader.dat",
    "DOS1Boot.zip",
    "DOS2Boot.zip",
    "NextorBoot.zip",
    "[OPL4].rom",
    "[ExtraPSG].rom"

];
